const devicesTable = [
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
  {
    deviceName: 'Ноутбук',
    ipAddress: '88.147.153.85',
    location: 'Russia',
    status: 'up',
  },
];

export default devicesTable;
