const devicesTable = [
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Планшет',
    ipAddress: '88.147.253.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Компьютер',
    ipAddress: '88.147.353.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Сервер',
    ipAddress: '88.147.453.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.553.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.247.653.98',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'down',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '12.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '12.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'down',
    date: '12.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'down',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'down',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'down',
    date: '15.02.2021',
  },
  {
    name: 'Ноутбук',
    ipAddress: '88.147.153.85',
    type: 'Router',
    location: 'Russia',
    coordinates: '',
    textarea: '',
    status: 'up',
    date: '15.02.2021',
  },
];

export default devicesTable;
